.TH lollypop 1 "Lollypop"
.SH NAME
.B Lollypop
\- a new GNOME music playing application
.SH SYNOPSIS
.B Lollypop
.RI [options]
.br
.SH DESCRIPTION
.B Lollypop
is a modern GNOME music player, with the following features:
.IP \[bu]
Artist bio, lyrics Artist bio, lyrics: Get artists and tracks information from the web.
.IP \[bu]
Intuitive browsing: Walk through your collection by genres/artists and through albums artwork.
.IP \[bu]
Play many audio formats: mp3, mp4, ogg, and flac
.IP \[bu]
Cover art downloader: Automatic artwork downloader from Last.fm, Itunes and Spotify.
.IP \[bu]
MTP devices: Sync your music with Android phones and any mtp devices…
.IP \[bu]
Fullscreen view: Visual access from your couch
.IP \[bu]
Party mode: Let Lollypop choose music for you.
.IP \[bu]
Native replay gain support.
.IP \[bu]
Search in your collection by artist, album and title.
.SH OPTIONS
.IP "-a, --play-ids"
Play ids
.IP "-d, --debug"
Debug Lollypop
.IP "-r, --set-rating"
Rate the current track
.IP "-t, --play-pause"
Toggle playback
.IP "-s, --stop"
Stop playback
.IP "-n, --next"
Go to next track
.IP "-p, --prev"
Go to prev track
.IP "-e, --emulate-phone"
Emulate a Librem phone
.IP "-v, --version"
Lollypop version
.IP "--display=DISPLAY"
X-display to use
.SH AUTHOR
.B Lollypop was written by Cédric Bellegarde
